apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: akashmondal0/react-native-backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: akash1234
        - name: MONGO_INITDB_DATABASE
          value: chatapp
        - name: REDIS_URL
          value: "redis://:akash1234@<local ip address>:6379"
        - name: JWT_SECRET
          value: "dRYjpuVfGUTCDttLnTON6KBP6q1kDLUD9oc"
        - name: KAFKA_BROKER
          value: "<local ip address>:9092"
        - name: CA_PATH
          value: "./src/kafka/ca.pem"
        - name: SASL_MECHANISM
          value: ""
        - name: SASL_USERNAME
          value: ""
        - name: SASL_PASSWORD
          value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000