version: '3.3'
services:
  db:
     image: mysql:latest
     ports:
       - "3306:3306"
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     container_name: mysql-containera
     networks:
      - some-net
     environment:
       MYSQL_ROOT_PASSWORD: akash@2003
       MYSQL_DATABASE: chatapp
       MYSQL_USER: akash
       MYSQL_PASSWORD: akash@2003

  # next-chat-client:
  #    depends_on:
  #      - db
  #    image: akashmondal0/next-chat:latest
  #   #  build:
  #   #   context: .
  #   #   dockerfile: Dockerfile
  #    container_name: client-container
  #    ports:
  #      - "3000:3000"
  #    volumes:
  #      - ./skystorage:/var/www/next-chat-client
  #    restart: always
  #    networks:
  #     - some-net
  #    environment:
  #      DATABASE_URL: mysql://root:akash@2003@mysql-container:3306/chatapp
  #      NEXT_PUBLIC_SOCKET_URL: http://locahost:3003

  next-chat-socket:
     depends_on:
       - db
    #  image: akashmondal0/socket-next-chat:latest
     build:
      context: ./socket-api
      dockerfile: dockerfile
     container_name: socket-container
     ports:
       - "3003:3003"
     volumes:
       - ./skystorage:/var/www/next-chat-socket
     restart: always
     networks:
      - some-net
volumes:
    db_data:
    skystorage:
networks:
  some-net:
    