version: '3.1'
services:
  server:
    image: akashmondal0/react-native-backend:latest
    restart: always
    ports:
      - 4000:4000
    environment:
      MONGODB_URI: "mongodb://root:akash1234@<local ip address>:27017/chatapp?authSource=admin"
      REDIS_URL: "redis://:akash1234@<local ip address>:6379"
      JWT_SECRET: "dRYjpuVfGUTCDttLnTON6KBP6q1kDLUD9oc"
      KAFKA_BROKER: "<local ip address>:9092"
      # for kafka ssl
      CA_PATH: "./src/kafka/ca.pem"
      SASL_MECHANISM: ""
      SASL_USERNAME: ""
      SASL_PASSWORD: ""

  client:
    image: akashmondal0/sky-chat-nextjs:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_HOST_URL: "http://localhost:4000"
      NEXT_PUBLIC_STORAGE_URL: "http://localhost:4001"

  storage:
    image: akashmondal0/sky-storage:latest
    restart: always
    ports:
      - 4001:4001
    container_name: storage
    volumes:
      - ./storage:/app/storage
    environment:
      PORT: 4001
      HOST: "http://localhost:4001"
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    restart: always
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins-lts
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /usr/bin/docker:/usr/bin/docker
      - ./jenkins_home:/var/jenkins_home
      # docker exec -it <container_id> cat /var/jenkins_home/secrets/initialAdminPassword

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: akash1234
      MONGO_INITDB_DATABASE: chatapp

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 60 1
    volumes:
      - ./rdata:/rdata
      - ./docker_datas/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: akash1234
      REDIS_PORT: 6379
      REDIS_DATABASES: 1
  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    environment:
      KAFKA_ZOOKEEPER_CONNECT: <local ip address>:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://<local ip address>:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER: <local ip address>:9092
    
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: <local ip address>:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://<local ip address>:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER: <local ip address>:9092

  prom-server:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
  
  grafana:
    image: grafana/grafana-oss:latest
    restart: always
    ports:
      - "3000:3000"

  grafana-loki:
    image: grafana/loki:latest
    restart: always
    ports:
      - "3100:3100"

